### PR TITLE
Updates for publishing

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR starts to reorganize some of the code to make it easier for others to replicate our figures and moves some of the validation work into an appendix

### CODE REVIEW

**Comment by rlskoeser** [comment]
@ZoeLeBlanc I apologize, I'm having a hard time reviewing this and understanding the changes - is most of this new code that wasn't in the repo before, or is some of it being reorganized?

Could you provide more context about what's changing to help me understand all of this by either adding some notes to the PR description or starting to add readmes to the different folders?  

Another option would be to stage the changes in smaller chunks over multiple PRs so it's easier to understand. I will do my best to review quickly if we go that route.

**Comment by ZoeLeBlanc** [comment]
No problem and apologies for creating such a big PR! Here's the breakdown of everything I did and happy to answer questions when we meet on Friday too:

1. Moved the logbooks and subscriptions table R scripts to the appendix and then converted them to one Rmarkdown notebook. The rationale was that we aren't using them in the paper anymore and notebooks are easier to rerun and document.
2. Split the giant missing borrowing activity into notebooks to correspond to the different subsections of the Missing Data section of the paper and moved that notebook and the altair one into an archived folder so that we would still have them for historic purposes.
3. The first subset notebook from that giant one is the MissingMembershipActivities notebook. This one is the code needed to generate the first three figures. There's probably some code missing for doing the manual calculations so that would be great to add in.
4. The second subset notebook is the MissingMembers notebook. This one is figures 4-6 and for this one, I moved some of the code to two scripts in a new scripts folder. The rationale was that we were reusing the same code to do the Prophet modeling and altair charts so this way we could keep this notebook a bit cleaner and reuse this code. Also still probably needs some of the manual calculations added back in.
5. The final other code is a ProphetValidation notebook where I tried to combine some of the experiments and validation code you had in the original missing borrowing notebook, so that people could see the validation attempts (though this could use more documentation). I'm again reusing those two scripts since a lot of that code got repeated and so this way it's really just showing the output of different parameters with Prophet.

As a general approach, I tried to add more Markdown headers and limit any displaying of data to just a row or two in less the dataframe was short so that everything could be readable for someone going through the code. 

Sorry again for doing this all in one giant PR. Was trying to just get it done since I figured I would take this on given that I need the updates for my students but realize that's makes more work for you to review, even if I'm trying to make less work 😅 . Anyways let me know if you have any questions and again happy to discuss on Friday 😊

**Comment by rlskoeser** [comment]
@ZoeLeBlanc thank you for explaining all of this. This also clarifies my confusion looking at the code when attempting to review the changes - I knew some of the code was yours (the R markdown and tables), but other parts of the code were familiar and I couldn't place them! Because of the way you've moved and reorganized — and, I think at a larger level, because we used notebooks and colab so extensively — the git history doesn't provide much in the way of credit and authorship. I was going to ask that you use my co-author commit email for code I wrote that you're moving around where you can't link it to the original file (and you've moved it and then made a bunch of improvements) - but maybe we can just add high-level description of authorship in the readmes or wherever else makes sense. This approach also gives us a way to acknowledge the parts that Kevin worked on, which we adapted and reworked.

We'll need to update the top-level readme and maybe add lower-level readmes to document the new structure, but I'm fine with doing that in a second pass. We can add it to our checklist. :-)

**Review by rlskoeser — APPROVED** [review]
Thanks for documenting your goals and steps in reorganizing all of this.  Makes a lot of sense that the notebooks as originally written, when we were still figuring things out, would be hard to make sense of for understanding the code, esp. as it relates to the article.

I'm ok with merging this based on your description of the changes you made and your goals with those changes.

**Pull request merged**
